version: '3.7'

services:

    project_name:
        container_name: project_name
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        environment:
            - MONGODB_URL=mongodb://admin:pass@mongo:27017/news?authSource=admin
            - PUBSUB_EMULATOR_HOST=pubsub_emulator:8432
            - PUBSUB_PROJECT_ID=fake_project
        entrypoint: ["npm", "run", "dev:context"]
        depends_on:
            - mongo
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
            - project_name_dist:/app/dist
            - project_name_node_modules:/app/node_modules
        ports:
            - 8080:8080

    mongo:
        image: mongo:7.0-jammy
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017

    mongo_express:
        image: mongo-express:1-20-alpine3.18
        container_name: mongo_express
        logging:
            driver: none
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@mongo:27017/daily-trends?authSource=admin
        ports:
            - 8081:8081

    pubsub_emulator:
        image: storytel/gcp-pubsub-emulator
        container_name: pubsub_emulator
        ports:
            - 8432:8432
        command: --host=0.0.0.0 --port=8432



volumes:
    project_name_node_modules:
    project_name_dist:
networks:
    default:
        name: project_name-environment-network
